# Python script that takes an OWL file in XML/RDF serialization and removes
# all the elements with an "internal:anonymous-constants" datatype. These 
# elements can easily be removed as they are duplicates generated by the 
# reasoning process in Protege that doesn't like custon datatypes


import argparse
from lxml import etree

def remove_elements_with_datatype(input_file, output_file, target_datatype="internal:anonymous-constants"):
    # XML-Datei einlesen
    parser = etree.XMLParser(remove_blank_text=True)
    tree = etree.parse(input_file, parser)
    root = tree.getroot()

    # Alle Elemente mit rdf:datatype="internal:anonymous-constants" finden und entfernen
    elements_to_remove = []
    for elem in root.iter():  # Durchlaufe alle Elemente
        for attr in elem.attrib:
            if attr.endswith("datatype") and elem.attrib[attr] == target_datatype:
                elements_to_remove.append(elem)

    # Entferne gefundene Elemente
    for elem in elements_to_remove:
        parent = elem.getparent()
        if parent is not None:
            parent.remove(elem)

    # Geänderte XML-Datei speichern
    tree.write(output_file, pretty_print=True, encoding="utf-8", xml_declaration=True)

# Kommandozeilen-Parameter verarbeiten
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Entfernt XML-Elemente mit rdf:datatype='internal:anonymous-constants'.")
    parser.add_argument("input_file", help="Pfad zur Eingabe-XML-Datei")
    parser.add_argument("output_file", help="Pfad zur Ausgabe-XML-Datei")
    args = parser.parse_args()

    remove_elements_with_datatype(args.input_file, args.output_file)
