# This is a basic workflow to help you get started with Actions

name: Widoco

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only when the owl file in "main" branch is changed
  push:
    branches: [ "main" ]
    paths:
      # Specify the file path to the ontology
      - 'MathModDB_full.owl'   
      # TODO: the following line added for testing purposes, remove it when the workflow is working
      - '.github/workflows/documentation.yml'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          ref: docstable


      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.1' # Specify the Python version to use

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Checkout owl file from main
        run: git fetch origin
             git checkout main
             git restore --source=main MathModDB_full.owl



      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
